spring:
  datasource:
    url: jdbc:mysql://localhost:3306/health_assistant?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 101895

logging:
  level:
    root: info
    org.health: debug

